[build]
  command = "npm ci && npm run build:netlify"
  publish = ".next"

[build.environment]
  NODE_OPTIONS = "--max_old_space_size=4096"
  NODE_VERSION = "18.18.0"
  NEXT_PUBLIC_BASE_URL = "https://dadlines.netlify.app"
  NEXTAUTH_URL = "https://dadlines.netlify.app"
  NEXTAUTH_SECRET = "dadlines-demo-secret-key"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/next_api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200

[context.production.environment]
  NODE_ENV = "production"

[functions]
  node_bundler = "esbuild"
  included_files = [".next/server/**", ".next/static/**"]

